In [1]:
#Randomly shuffle the single cell data and split it into training and test sets

#For cases where diff number of samples are used as training etc.
#python3 train_test_validation_split.py --path_input ../../data/PI_Segerstolpe_scRS/all_patients/4_ --path_save ../../data/PI_Segerstolpe_scRS/all_patients/train_valid_test/4_
#python3 train_test_validation_split.py --path_input ../../data/PI_Segerstolpe_scRS/all_patients/6_ --path_save ../../data/PI_Segerstolpe_scRS/all_patients/train_valid_test/6_

import numpy as np
import pandas as pd
import os
from numpy import savetxt
import random
import argparse
'''
parser = argparse.ArgumentParser(description='Train_test_validation split datasets')
parser.add_argument('--path_input', type=str, default='../../../RA/other_datasets/HBC_NSR/', help='path to input files')
parser.add_argument('--path_save', type=str, default='../../../RA/other_datasets/HBC_NSR/train_valid_test/', help='path to save results')

args = parser.parse_args()

'''
path_input = '../1.Counts_and_cells/Mammary/'
path_save = '../2.Counts_and_cells_train_test/Mammary/'

In [2]:
# Get prior probabilities
with open(path_input+'cell_labels_oh.csv','r') as f:
    prior = pd.read_csv(f,sep=",",header=None)
#with open(args.path_input+'cell_labels_oh_7celltypes.csv','r') as f:
#    prior = pd.read_csv(f,sep=",",header=None)
#with open(args.path_input+'cell_labels_oh_ordered.csv','r') as f:
#    prior = pd.read_csv(f,sep=",",header=None)

In [4]:

with open(path_input+'counts_matrix_all.tab','r') as f:
    XA = pd.read_csv(f,sep="\t" , index_col="Unnamed: 0")
'''

with open(path_input+'counts_matrix_all_normr.tab','r') as f:
    XAn = pd.read_csv(f,sep="\t")

with open(path_input+'counts_matrix_all_log1p_normr.tab','r') as f:
    XAln = pd.read_csv(f,sep="\t")

with open(path_input+'counts_matrix_pp.tab','r') as f:
    X = pd.read_csv(f,sep="\t")

with open(path_input+'counts_matrix_pp_normr.tab','r') as f:
    Xn = pd.read_csv(f,sep="\t")

with open(path_input+'counts_matrix_pp_log1p_normr.tab','r') as f:
    Xln = pd.read_csv(f,sep="\t")

with open(path_input+'counts_matrix_hvg.tab','r') as f:
    Xv = pd.read_csv(f,sep="\t")

with open(path_input+'counts_matrix_hvg_normr.tab','r') as f:
    Xvn = pd.read_csv(f,sep="\t")

with open(path_input+'counts_matrix_hvg_log1p_normr.tab','r') as f:
    Xvln = pd.read_csv(f,sep="\t")
'''
print('shuffle')
print(len(XA))

shuffle
11340

In [4]:
prior

        0    1    2    3    4    5    6
0     0.0  0.0  0.0  0.0  1.0  0.0  0.0
1     0.0  0.0  0.0  0.0  1.0  0.0  0.0
2     0.0  0.0  0.0  0.0  1.0  0.0  0.0
3     0.0  0.0  0.0  0.0  1.0  0.0  0.0
4     0.0  0.0  0.0  0.0  1.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...
4925  0.0  0.0  0.0  0.0  1.0  0.0  0.0
4926  0.0  0.0  0.0  0.0  1.0  0.0  0.0
4927  0.0  0.0  0.0  0.0  1.0  0.0  0.0
4928  0.0  0.0  0.0  0.0  1.0  0.0  0.0
4929  0.0  0.0  0.0  0.0  1.0  0.0  0.0

[4930 rows x 7 columns]

In [5]:
index = list(range(len(XA)))
random.seed(1000)
random.shuffle(index)
#with open(args.path_input+'cell_labels_oh_ordered.csv','r') as f:
#    prior = pd.read_csv(f,sep=",",header=None)

In [6]:
XA_shuffled = XA.iloc[index]
prior_shuffled = prior.iloc[index]

In [ ]:
'''
Xn_shuffled = Xn.iloc[index]
Xln_shuffled = Xln.iloc[index]
'''

In [ ]:
'''
Xv_shuffled = Xv.iloc[index]
Xvn_shuffled = Xvn.iloc[index]
Xvln_shuffled = Xvln.iloc[index]
#XA_shuffled = XA.iloc[index]
#XAn_shuffled = XAn.iloc[index]
#XAln_shuffled = XAln.iloc[index]


print(X_shuffled)
print(prior_shuffled)
print(Xn_shuffled)
print(Xln_shuffled)
print(Xv_shuffled)
print(Xvn_shuffled)
'''

In [7]:
#Split training:validation:test in 70:10:20 ratio
num_training = int(len(XA))# * 0.8) #we do not need the train/test
#num_validation = int(len(X) * 0.8)#we won't take this

In [8]:
num_training

11340

In [9]:
train_prior = prior_shuffled[:num_training]
train_prior = train_prior.to_numpy()

In [ ]:
'''
train_X = X_shuffled[:num_training].copy()
train_X= train_X.drop(train_X.columns[0], axis = 1)
train_Xn = Xn_shuffled[:num_training].copy()
train_Xn = train_Xn.drop(train_Xn.columns[0], axis = 1)
train_Xln = Xln_shuffled[:num_training].copy()
train_Xln = train_Xln.drop(train_Xln.columns[0], axis = 1)
train_Xv = Xv_shuffled[:num_training].copy()
train_Xv = train_Xv.drop(train_Xv.columns[0], axis = 1)
train_Xvn = Xvn_shuffled[:num_training].copy()
train_Xvn = train_Xvn.drop(train_Xvn.columns[0], axis = 1)
train_Xvln = Xvln_shuffled[:num_training].copy()
train_Xvln = train_Xvln.drop(train_Xvln.columns[0], axis = 1)
train_XAn = XAn_shuffled[:num_training].copy()
train_XAn = train_XAn.drop(train_XAn.columns[0], axis = 1)
train_XAln = XAln_shuffled[:num_training].copy()
train_XAln = train_XAln.drop(train_XAln.columns[0], axis = 1)
'''

In [10]:
train_XA = XA_shuffled[:num_training].copy()
#train_XA = train_XA.drop(train_XA.columns[0], axis = 1)

In [11]:
train_XA

,DDX11L1,WASH7P,MIR6859.1,MIR1302.2HG,MIR1302.2,FAM138A,OR4G4P,OR4G11P,OR4F5,AL627309.1,...,MT.ND4,MT.TH,MT.TS2,MT.TL2,MT.ND5,MT.ND6,MT.TE,MT.CYB,MT.TT,MT.TP
5774,0,0,0,0,0,0,0,0,0,0,...,26,0,0,0,12,8,0,20,0,0
9053,0,0,0,0,0,0,0,0,0,0,...,96,0,0,0,30,2,0,46,0,0
3327,0,0,0,0,0,0,0,0,0,0,...,44,0,0,0,5,2,0,30,0,0
1019,0,0,0,0,0,0,0,0,0,0,...,185,0,0,0,35,2,0,137,0,0
3726,0,0,0,0,0,0,0,0,0,0,...,38,0,0,0,2,0,0,29,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5794,0,0,0,0,0,0,0,0,0,0,...,8,0,0,0,2,0,0,3,0,0
6459,0,0,0,0,0,0,0,0,0,0,...,54,0,0,0,8,0,0,52,0,0
1625,0,0,0,0,0,0,0,0,0,0,...,130,0,0,0,18,0,0,101,0,0
11006,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,4,0,0,0,0,0
7041,0,0,0,0,0,0,0,0,0,0,...,5,0,0,0,3,0,0,2,0,0

In [ ]:
'''
validation_X = X_shuffled[num_training:num_validation].copy()
validation_X = validation_X.drop(validation_X.columns[0], axis = 1)
validation_prior = prior_shuffled[num_training:num_validation]
validation_prior = validation_prior.to_numpy()
validation_Xn = Xn_shuffled[num_training:num_validation].copy()
validation_Xn = validation_Xn.drop(validation_Xn.columns[0], axis = 1)
validation_Xln = Xln_shuffled[num_training:num_validation].copy()
validation_Xln = validation_Xln.drop(validation_Xln.columns[0], axis = 1)
validation_Xv = Xv_shuffled[num_training:num_validation].copy()
validation_Xv = validation_Xv.drop(validation_Xv.columns[0], axis = 1)
validation_Xvn = Xvn_shuffled[num_training:num_validation].copy()
validation_Xvn = validation_Xvn.drop(validation_Xvn.columns[0], axis = 1)
validation_XA = XA_shuffled[num_training:num_validation].copy()
validation_XA = validation_XA.drop(validation_XA.columns[0], axis = 1)
validation_XAn = XAn_shuffled[num_training:num_validation].copy()
validation_XAn = validation_XAn.drop(validation_XAn.columns[0], axis = 1)
validation_XAln = XAln_shuffled[num_training:num_validation].copy()
validation_XAln = validation_XAln.drop(validation_XAln.columns[0], axis = 1)

'''

In [12]:
num_validation = num_training

In [13]:
num_validation

11340

In [14]:
test_prior = prior_shuffled[num_validation:]
test_prior = test_prior.to_numpy()

test_XA = XA_shuffled[num_validation:].copy()
#test_XA =test_XA.drop(test_XA.columns[0], axis = 1)

In [ ]:
'''
test_X = X_shuffled[num_validation:].copy()
test_X = test_X.drop(test_X.columns[0], axis = 1)

test_Xn = Xn_shuffled[num_validation:].copy()
test_Xn = test_Xn.drop(test_Xn.columns[0], axis = 1)
test_Xln = Xln_shuffled[num_validation:].copy()
test_Xln = test_Xln.drop(test_Xln.columns[0], axis = 1)
test_Xv = Xv_shuffled[num_validation:].copy()
test_Xv = test_Xv.drop(test_Xv.columns[0], axis = 1)
test_Xvn = Xvn_shuffled[num_validation:].copy()
test_Xvn = test_Xvn.drop(test_Xvn.columns[0], axis = 1)

test_Xvln = Xvln_shuffled[num_validation:].copy()
test_Xvln = test_Xvln.drop(test_Xvln.columns[0], axis = 1)

test_XAn = XAn_shuffled[num_validation:].copy()
test_XAn = test_XAn.drop(test_XAn.columns[0], axis = 1)
test_XAln = XAln_shuffled[num_validation:].copy()
test_XAln = test_XAln.drop(test_XAln.columns[0], axis = 1)

'''

In [15]:
test_XA

Empty DataFrame
Columns: [DDX11L1, WASH7P, MIR6859.1, MIR1302.2HG, MIR1302.2, FAM138A, OR4G4P, OR4G11P, OR4F5, AL627309.1, AL627309.3, CICP27, AL627309.6, AL627309.7, AL627309.2, AL627309.5, RNU6.1100P, AL627309.4, FO538757.1, WASH9P, MIR6859.2, AP006222.1, RPL23AP24, AL732372.1, AL732372.2, WBP1LP7, OR4F29, CICP7, AL732372.3, RF00026, AL669831.3, AC114498.1, MTND1P23, MTND2P28, MTCO1P12, AC114498.2, MTCO2P12, MTATP8P1, MTATP6P1, MTCO3P12, WBP1LP6, OR4F16, CICP3, AL669831.1, RNU6.1199P, AL669831.2, AL669831.5, AL669831.7, AL669831.4, FAM87B, LINC01128, LINC00115, FAM41C, TUBB8P11, AL669831.6, AL645608.6, AL645608.2, AL645608.4, LINC02593, SAMD11, NOC2L, KLHL17, PLEKHN1, PERM1, AL645608.7, HES4, ISG15, AL645608.3, AL645608.1, AGRN, AL645608.5, AL390719.1, AL645608.8, RNF223, C1orf159, AL390719.3, LINC01342, MIR200B, MIR200A, MIR429, AL390719.2, TTLL10.AS1, TTLL10, TNFRSF18, TNFRSF4, SDF4, B3GALT6, C1QTNF12, AL162741.1, UBE2J2, LINC01786, SCNN1D, ACAP3, MIR6726, PUSL1, INTS11, MIR6727, AL139287.1, CPTP, TAS1R3, ...]
Index: []

[0 rows x 58870 columns]

In [16]:
#train_X.to_csv(path_save+'counts_matrix_pp_train.tab',sep="\t")
savetxt(path_save+'cell_labels_oh_train.csv',train_prior,delimiter=",")

In [ ]:
'''
validation_X.to_csv(path_save+'counts_matrix_pp_validation.tab',sep="\t")
savetxt(path_save+'cell_labels_oh_validation.csv',validation_prior,delimiter=",")
'''

In [17]:
#test_X.to_csv(path_save+'counts_matrix_pp_test.tab',sep="\t")
savetxt(path_save+'cell_labels_oh_test.csv',test_prior,delimiter=",")

In [18]:
train_XA.to_csv(path_save+'counts_matrix_all_train.tab',sep="\t")
#validation_XA.to_csv(path_save+'counts_matrix_all_validation.tab',sep="\t")
#test_XA.to_csv(path_save+'counts_matrix_all_test.tab',sep="\t")

In [ ]:
'''
train_Xn.to_csv(path_save+'counts_matrix_pp_normr_train.tab',sep="\t")
#validation_Xn.to_csv(path_save+'counts_matrix_pp_normr_validation.tab',sep="\t")
#test_Xn.to_csv(path_save+'counts_matrix_pp_normr_test.tab',sep="\t")

train_Xln.to_csv(path_save+'counts_matrix_pp_log1p_normr_train.tab',sep="\t")
#validation_Xln.to_csv(path_save+'counts_matrix_pp_log1p_normr_validation.tab',sep="\t")
#test_Xln.to_csv(path_save+'counts_matrix_pp_log1p_normr_test.tab',sep="\t")
train_Xv.to_csv(path_save+'counts_matrix_hvg_train.tab',sep="\t")
#validation_Xv.to_csv(path_save+'counts_matrix_hvg_validation.tab',sep="\t")
#test_Xv.to_csv(path_save+'counts_matrix_hvg_test.tab',sep="\t")

train_Xvn.to_csv(path_save+'counts_matrix_hvg_normr_train.tab',sep="\t")
#validation_Xvn.to_csv(path_save+'counts_matrix_hvg_log1p_normr_validation.tab',sep="\t")
#test_Xvn.to_csv(path_save+'counts_matrix_hvg_normr_test.tab',sep="\t")
train_Xvln.to_csv(path_save+'counts_matrix_hvg_log1p_normr_train.tab',sep="\t")
#validation_Xvn.to_csv(path_save+'counts_matrix_hvg_log1p_normr_validation.tab',sep="\t")
#test_Xvln.to_csv(path_save+'counts_matrix_hvg_log1p_normr_test.tab',sep="\t")
train_XAn.to_csv(path_save+'counts_matrix_all_normr_train.tab',sep="\t")
#validation_XAn.to_csv(path_save+'counts_matrix_all_normr_validation.tab',sep="\t")
#test_XAn.to_csv(path_save+'counts_matrix_all_normr_test.tab',sep="\t")
train_XAln.to_csv(path_save+'counts_matrix_all_log1p_normr_train.tab',sep="\t")
#validation_XAln.to_csv(path_save+'counts_matrix_all_log1p_normr_validation.tab',sep="\t")
#test_XAln.to_csv(path_save+'counts_matrix_all_log1p_normr_test.tab',sep="\t")
'''

In [ ]:
test_XA